# Generated by Django 6.0.1 on 2026-01-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date_sold',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='quantity_sold',
            new_name='quantity',
        ),
    ]
