# Generated by Django 6.0.1 on 2026-01-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_date_sold_sale_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='price',
            new_name='total_amount',
        ),
    ]
